-- -- 表单设计器菜单
-- -- 父菜单: 表单设计器
-- -- 子菜单1: 表单列表 -> /form-designer/list
-- -- 子菜单2: 数据库配置 -> /form-designer/database
--
-- -- 父菜单ID（使用 WHERE NOT EXISTS 防止重复插入）
-- SET @parent_id = 'a943f3c6-7762-4daa-9ee5-5d8f49ec8a9e';
-- SET @child_list_id = 'b943f3c6-7762-4daa-9ee5-5d8f49ec8a9e';
-- SET @child_db_id = 'c943f3c6-7762-4daa-9ee5-5d8f49ec8a9e';
--
-- INSERT INTO sys_menu(
--     id, parent_id, tree_index, child_count, full_child_count,
--     tree_level, tree_code, full_tree_code, function_id,
--     name, uri, param, description, type, icon, sort,
--     is_active, create_by, create_datetime, last_modify_by, last_modify_datetime,
--     system_type, is_hidden, target
-- )
-- SELECT @parent_id, NULL, @parent_id, 2, 2, 1, ' ', ' ', NULL,
--        '表单设计器', '  ', ' ', ' ', 'menu', 'fa fa-wpforms', 350,
--        1, 'system', NOW(), 'system', NOW(), 0, 0, ' '
-- WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id = @parent_id);
--
-- INSERT INTO sys_menu(
--     id, parent_id, tree_index, child_count, full_child_count,
--     tree_level, tree_code, full_tree_code, function_id,
--     name, uri, param, description, type, icon, sort,
--     is_active, create_by, create_datetime, last_modify_by, last_modify_datetime,
--     system_type, is_hidden, target
-- )
-- SELECT @child_list_id, @parent_id, @child_list_id, 0, 0, 2, ' ', ' ', NULL,
--        '表单列表', '/form-designer/list', ' ', ' ', 'menu', 'fa fa-list-alt', 1,
--        1, 'system', NOW(), 'system', NOW(), 0, 0, ' '
-- WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id = @child_list_id);
--
-- INSERT INTO sys_menu(
--     id, parent_id, tree_index, child_count, full_child_count,
--     tree_level, tree_code, full_tree_code, function_id,
--     name, uri, param, description, type, icon, sort,
--     is_active, create_by, create_datetime, last_modify_by, last_modify_datetime,
--     system_type, is_hidden, target
-- )
-- SELECT @child_db_id, @parent_id, @child_db_id, 0, 0, 2, ' ', ' ', NULL,
--        '数据库配置', '/form-designer/database', ' ', ' ', 'menu', 'fa fa-database', 2,
--        1, 'system', NOW(), 'system', NOW(), 0, 0, ' '
-- WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id = @child_db_id);
